safe: true
lsi: false
pygments: true
permalink: pretty
paginate: 10
auto: true

name: "MichaelBlatherwick.co.uk"
s3_bucket: http://s3-eu-west-1.amazonaws.com/exonian/
s3_photos: http://s3-eu-west-1.amazonaws.com/exonian/website_photos/
